# This module encapsulates all database operations for Employee
# Abstracts away raw DB queries from the API routes, keeping the code modular
# Keeps DB logic separate and reusable, making the app cleaner and easier to maintain
    # refresh():
# Reloads the object from DB to get autogenerated fields (id)

from sqlalchemy.orm import Session
import models
import schema

def get_employees(db: Session): 
    return db.query(models.Employee).all()

def get_employee(db: Session, employee_id: int):
    return db.query(models.Employee).filter(models.Employee.id == employee_id).first()  

def create_employee(db: Session, employee: schema.EmployeeCreate):
    db_employee = models.Employee(name=employee.name, email=employee.email)
    db.add(db_employee)
    db.commit()
    db.refresh(db_employee) 
    return db_employee

def update_employee(db: Session, employee_id: int, employee: schema.EmployeeUpdate):
    db_employee = db.query(models.Employee).filter(models.Employee.id == employee_id).first()
    if db_employee:
        db_employee.name = employee.name
        db_employee.email = employee.email
        db.commit()
        db.refresh(db_employee)
    return db_employee

def delete_employee(db: Session, employee_id: int):
    db_employee = db.query(models.Employee).filter(models.Employee.id == employee_id).first()
    if db_employee:
        db.delete(db_employee)
        db.commit()
    return db_employee 



